"""create product table

Revision ID: 7e3576b1b6d8
Revises: 
Create Date: 2026-08-11 20:56:55.357338
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel's own column types are referenced by the autogenerated code
from alembic import op


revision: str = '7e3576b1b6d8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_in_stock'), ['in_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_stock'), ['stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_uuid'))
        batch_op.drop_index(batch_op.f('ix_product_stock'))
        batch_op.drop_index(batch_op.f('ix_product_rating'))
        batch_op.drop_index(batch_op.f('ix_product_price'))
        batch_op.drop_index(batch_op.f('ix_product_name'))
        batch_op.drop_index(batch_op.f('ix_product_in_stock'))
        batch_op.drop_index(batch_op.f('ix_product_category'))

    op.drop_table('product')
    # ### end Alembic commands ###
